### ISSUE TITLE
Loadbalancer : Update command fails

### ISSUE THREAD

**Issue by vikasmathod** [MSOpenTech/azure-sdk-tools-xplat#110]
Step 1: Add a internal load balancer for a cloud service deployment.
Step 2: Use update commands on the load balancer . The command fails 

![loadbalancing1](https://cloud.githubusercontent.com/assets/6801546/5042582/09b1a3e2-6bfe-11e4-8025-260b11991829.PNG)
![loadbalancing2](https://cloud.githubusercontent.com/assets/6801546/5042581/09b07e72-6bfe-11e4-84ce-0188877d126b.PNG)

**Comment by babumuralidharan** [comment]
This issue is fixed in the prod version. Update command works now.

![image](https://cloud.githubusercontent.com/assets/1501823/6341857/7d1d43c4-bb84-11e4-9626-0fe9bc692453.png)
