### ISSUE TITLE
HPC Testing: * Azure CLI requires –c option to put multiple VMs in a cloud service 

### ISSUE THREAD

**Issue by kmouss** [MSOpenTech/azure-sdk-tools-xplat#120]
* Azure CLI requires –c option to put multiple VMs in a cloud service – Adding a second VM to a cloud service without this simply returns a failure.   

o Solution – Use the –c option at all times with the CLI, as it has no known negative impact.  (Why is this not always enabled?)

**Comment by kmouss** [comment]
Since the user has to put the Cloud service name any way, I don't think this option (-c) is very useful and causes confusion since if you don't specify it in the case where you plan to put the VM in the same cloud service it will fail and the help isn't super clear on what is wrong until you dig further. Thanks,

**Comment by babumuralidharan** [comment]
This is the only flag which gives control to the user whether he can create multiple VMs under same cloudservice or new one. So removing this or assuming -c option  by default simply overrides user's actual intention. So i think we should leave this behavior intact. Closing this issue. If you still feel this needs to be opened please add this in azure repo.
