### ISSUE TITLE
HPC Testing: * Azure CLI requires location even when it will be ignored * Azure CLI requires location even when it will be ignored 

### ISSUE THREAD

**Issue by kmouss** [MSOpenTech/azure-sdk-tools-xplat#121]
* Azure CLI requires location even when it will be ignored – This is a known bug in the CLI – location or affinity group is required to get some commands to run even when they will be ignored at run time. 

o Solution – Always provide a location, as doing so has no known negative impact.

**Comment by babumuralidharan** [comment]
Closing this since we are tracking the same in https://github.com/Azure/azure-xplat-cli/issues/1283
