### ISSUE TITLE
HPC Testing: * Azure CLI requires 4 types of characters in the password 

### ISSUE THREAD

**Issue by kmouss** [MSOpenTech/azure-sdk-tools-xplat#122]
* Azure CLI requires 4 types of characters in the password – Not all interfaces require the same restrictions on passwords – this seems to be the most restrictive (requires upper, lower, number and symbol). 

o Solution – Use all four when creating any password.  This can be an issue in some command lines as certain characters (like ‘$’) have other meanings.  The ‘@’ symbol appears to be safe everywhere.

**Comment by babumuralidharan** [comment]
I guess above comments provide enough justifications for this issue. Closing this issue since this is a default behavior of shell.
