### ISSUE TITLE
HPC Testing: Support creating a VNet without a default Affinity group. 

### ISSUE THREAD

**Issue by kmouss** [MSOpenTech/azure-sdk-tools-xplat#126]
VNets created in some environments have affinity groups by default – Not having affinity groups here is new.  When creating a VNet with the CLI (as an example), by default it creates an affinity group to go with it if one is not specified. 
o Solution in scripting – Harder to do, but download the current VNet configuration, edit in a new VNet without an affinity group, and upload the new configuration. 
o Solution in general – VNets can be created without affinity groups in the portal.

**Comment by babumuralidharan** [comment]
This issue has been fixed and by default we create region wise vnet. If user specifies --create-new-affinity-group then we create affinity group vnet. This is working fine in 0.8.15.
