### ISSUE TITLE
azure vm create -u switch being used twice for both username and bloburl

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-sdk-tools-xplat#127]
Refer screenshot for more details on this issue. Vm create help command should be similar to that of vm docker create command where username is a mandatory parameter

![image](https://cloud.githubusercontent.com/assets/10084788/5919131/a99c25b6-a656-11e4-8652-51418ea8e926.png)

**Comment by babumuralidharan** [comment]
Closing this since we are tracking this in azure repo
