### ISSUE TITLE
cloud service creation fails if user passes only virtual network name when creating VM

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/azure-sdk-tools-xplat#35]
Create VNET under a  location.
Create VM with giving this VNET as a parameter without passing location & affinitygroup. 
New Cloudservice creation step fails and create vm fails.

In vm client we are handling the same scenario if VNET is created under a affinity group.

Also same case needs to be checked if user creates vm in existing cloudservice and user specifies only VNET.

**Comment by orangemocha** [comment]
Fixed in https://github.com/MSOpenTech/azure-sdk-tools-xplat/commit/ccf09dbf13a54a536c3d9cee2615be62d18bced6
