### ISSUE TITLE
docker vm create on failure do not delete cloudservice

### ISSUE THREAD

**Issue by babumuralidharan** [MSOpenTech/azure-sdk-tools-xplat#43]
when an exception occurs during docker vm create, it should delete the cloudservice that was created during command run which is not happening currently. The error callback do not handle the hosted service deletion part in createDockerVM function. This behavior is inconsistent with vm create command.

**Comment by orangemocha** [comment]
Fixed in https://github.com/MSOpenTech/azure-sdk-tools-xplat/commit/b2bfde7fb1ae50ae38c398c27dc9d936d4c4f89f
